### ISSUE TITLE
Create "Note" screen (for adding note, editing note, and viewing note)

### ISSUE THREAD

**Issue by DarthVanger** [DarthVanger/NeuralNotes#100]
Currently when user double-clicks the note, a new node is added to the mind map, and an editor is shown to edit the new note name:

![image](https://user-images.githubusercontent.com/6686679/96149868-79aad980-0f12-11eb-90c5-5d38b29fb308.png)

But according to [the new design](https://www.figma.com/file/FxmwqO6LRg7tOVXrZqMMG0/Neural-Notes-Design-v.0.3?node-id=212%3A836) the "add note" should be a separate screen (and the same screen serves as "edit note" and "view note"):

![image](https://user-images.githubusercontent.com/6686679/96150007-a2cb6a00-0f12-11eb-97a1-a2800009650b.png)

So when user double-clicks a note to create a new note, we should change page to "note page", instead of showing an editor on the same page.

What is to be done:
1. Create a new page "Note page". This page will be used for adding a new note, editing a note, and for viewing a note.
2. When user double-clicks a note, redirect to the "Note page".
3. Move `NoteDetailsContainer` from the MindMap page to the "Note page"

![image](https://user-images.githubusercontent.com/6686679/96236446-b9220600-0fa4-11eb-948b-82a4ae6681d1.png)

**Comment by DarthVanger** [comment]
I've created a separate task to add the "saving..." indicator: #153, so we can do work in smaller chunks

**Comment by kvoncode** [comment]
Closed by https://github.com/DarthVanger/NeuralNotes/pull/167
