### ISSUE TITLE
Component rendering refactoring

### ISSUE THREAD

**Issue by DarthVanger** [DarthVanger/NeuralNotes#11]
Currently component rendering is quite a mess.

We might need React or smth like this to enable:
1. Easy nested components rendering.
2. Rerender with proper cleanup.

**Comment by milieuChris** [comment]
This is a very cool little project. Nice idea! 

How invested are you in a specific framework? Is there something specific that you want to learn? What i see here can be done quite cleanly with an API first approach. Node (or anything else for that matter) on the backend with web components straight out of the W3C spec. This will make the workflow easier when it comes time to work with a designer. Any reactive style framework will do for managing state change (basically only the Google Drive folder structure from what i see here). 

Cheers for the idea in any case!

**Comment by DarthVanger** [comment]
@milieuChris thanks for the warm comment :)

I'm not invested in any particular framework. Web components sounds cool.

Not sure though if it make sense to use Web components straight out of the W3C spec, because it looks quite tedious? Maybe some library can be used to reduce the boilerplate?

What do you mean by the API first approach for this case? I was going to have a server for serving static resources only, and query Google Drive (or potentially other cloud file storage) from the client directly, to avoid the need of extra backend infrastructure. I would use frontend storage (localStorage and/or new stuff like IndexedDB) for caching things on frontend.

**Comment by milieuChris** [comment]
Client side storage is certainly good, but the user may come back from a different device. I was thinking that there would need to be server side state for project configuration such as the name of the folder to start from and user preferences such as visual styles. I was also thinking of sharing use cases as mind maps are often a group exercise and drive folders are often shared between individuals and groups.

If there is no server side state stored then the application can always start at the root of the user’s Drive folder. I did not dig deep enough into the code to see if the name of the folder is a hard coded but a simple configuration file could be saved on the user’s Google Drive root if that is the only configuration that needs to be maintained between devices. I only saw the project using Express, so thought you might be using (or intending to use) that in a monolithic server way. If there is no state other than Google Drive itself and you are not doing any server side routing then you do not even need Express. 

There really is not much to Web Components but right, you want something for client side routes (a specialized form of state really) and potentially for other message/state passing. The rest is super simple JS though so i’m just pondering the most minimal ways to approach this. There are lighter frameworks than React, but i do not have a specific favorite. They are all temporary projects in my view — we are all learning too quickly and the web specs move too fast. 

I definitely think you are on the right track thinking about static resources and client side caching!

**Comment by milieuChris** [comment]
Well let me know how i can help! I've starred and watch to track progress. Would love to see where you decide to take this.

**Comment by DarthVanger** [comment]
@milieuChris thank you!
Did you come here from [the job I posted on Ethlance](https://ethlance.com/#/job/390)?

**Comment by milieuChris** [comment]
@DarthVanger Yes, that is how i found you, but i do not have anything in Ethereum right now. I'm tracking future of work and value attribution projects. 

I just thought the idea was cool. If you do want to turn this into a revenue type thing we can talk here:  chris@milieu.us

**Comment by DarthVanger** [comment]
The app is now using React components.
