### ISSUE TITLE
Uploads screen: new design

### ISSUE THREAD

**Issue by DarthVanger** [DarthVanger/NeuralNotes#118]
## New UX

When uploads screen has no items to display, show "no items" as per design:

https://www.figma.com/file/fpIeNN3IFhUOuxg6LHysgW/Neural-Notes-Design-Pending-(Copy)?node-id=0%3A1

![image](https://user-images.githubusercontent.com/6686679/87875552-a23a3a80-c9da-11ea-95e4-32a9fd22aa29.png)

we have new design [here](https://www.figma.com/file/FxmwqO6LRg7tOVXrZqMMG0/Neural-Notes-Design-v.0.3?node-id=212%3A836)

current view is 

when there are no any uploads
![Screenshot_3](https://user-images.githubusercontent.com/19979138/93685772-6135d380-faba-11ea-8f8c-6e5a80ea4f76.png)

when there is/are some upload/uploads
![Screenshot_4](https://user-images.githubusercontent.com/19979138/93685818-90e4db80-faba-11ea-9cb1-c5ea07edfadf.png)

and screen with uploads
![Screenshot_5](https://user-images.githubusercontent.com/19979138/93685829-a3f7ab80-faba-11ea-93d1-0d8228f9a819.png)

## Current UX

Currently the user can't open the uploads screen if there are no uploads.

The new design has "clear all" button, so we will need to show "no items".

**Comment by TomaTomoe** [comment]
In order to new design should to be discuss. Do we need to show this screen for user when he doesn't has any uploads? We discussed the way when link to this page will appear only when user has uploads.

**Comment by DarthVanger** [comment]
> In order to new design should to be discuss. Do we need to show this screen for user when he doesn't has any uploads? We discussed the way when link to this page will appear only when user has uploads.

Yes let's show the uploads button only when the user has uploads, and so we don't need the "no items" text.

Could you please document this functionality in the design and create a task to show the uploads button only when the user has uploads? So we would have all the info about the UX for the other team members to understand how should it work.
