### ISSUE TITLE
Note Details: Hide when neccessary

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#127]
The NoteDetails componet must be hidden when:
-  root note is selected;
- file is selected.

**Comment by DarthVanger** [comment]
NoteDetails component was removed after a redesign.
Closing as outdated https://www.figma.com/file/Fp2ZxU4bz0i5LvbOFq8xlY/Neural-Notes-Design-v.0.2.2?node-id=212%3A836
