### ISSUE TITLE
Implement drop-down for hamburger menu in topbar using material-ui

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#134]
Implement drop-down menu
[Figma](https://www.figma.com/file/FxmwqO6LRg7tOVXrZqMMG0/Neural-Notes-Design-v.0.3) 
![IMG_20200913_183436](https://user-images.githubusercontent.com/19979138/93022108-ccc9fd80-f5ef-11ea-8998-b7ce72e89257.jpg)
using
[material-ui -> menu component](https://material-ui.com/ru/components/menus/)

**Comment by DarthVanger** [comment]
Closing in favor of https://github.com/DarthVanger/NeuralNotes/issues/133
