### ISSUE TITLE
Implement add new note button functionality

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#135]
We have a button for add new note:

[Figma](https://www.figma.com/file/FxmwqO6LRg7tOVXrZqMMG0/Neural-Notes-Design-v.0.3) 

![IMG_20200913_185951](https://user-images.githubusercontent.com/19979138/93022726-61822a80-f5f3-11ea-88b7-9eaffed873fe.jpg)

But it does nothing on click.

It should let the user create a new note on click.

**Comment by DarthVanger** [comment]
Isn't this task done already?
