### ISSUE TITLE
Implement Bottom App Bar using material-ui

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#137]
Implement Bottom App Bar using [material-ui](https://material-ui.com/components/app-bar/#bottom-app-bar) bottom-app-bar [component](https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/app-bar/BottomAppBar.js)

[New design](https://www.figma.com/file/FxmwqO6LRg7tOVXrZqMMG0/Neural-Notes-Design-v.0.3)

![Screenshot_28](https://user-images.githubusercontent.com/19979138/93717979-c43e6d80-fb81-11ea-8acf-fa7c8136b4c3.png)

**Comment by DarthVanger** [comment]
@Batsvinova-Anastasiia has done it already
