### ISSUE TITLE
Edit/Open note: add buttons

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#138]
**Update: Use pencil icon instead of  ![Screenshot_13](https://user-images.githubusercontent.com/19979138/93689178-ae26a380-fad4-11ea-8a7d-4583e4649bed.png)**

Redirect to `/note` page. When user choose "Edit" in dropdown menu or open note by click on this icon ![Screenshot_13](https://user-images.githubusercontent.com/19979138/93689178-ae26a380-fad4-11ea-8a7d-4583e4649bed.png) in bottom app bar
![Screenshot_37](https://user-images.githubusercontent.com/19979138/94176362-a97d3900-fea0-11ea-9c1a-4029b7f6cadf.png)

We already have the button with functionality to redirect to the `/note` page (it is implemented in #100). We just need to update the styles.

![image](https://user-images.githubusercontent.com/6686679/97104810-6391db80-16bf-11eb-8e4d-d4c09c466dff.png)

**Comment by DarthVanger** [comment]
Opening a note details on click & hold sounds weird to me: usually on hold an item would be selected, or a context menu would be shown. Let's drop this functionality.
So a note details would be opened in 2 cases:
- when the user clicks "edit" in the dropdown menu
- when the user clicks the ![image](https://user-images.githubusercontent.com/6686679/93689485-96045380-fad7-11ea-8641-ccc9e63b449a.png) icon.
