### ISSUE TITLE
Make an architecture decision about AppBar

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#140]
Currently we have several state or view of AppBar. We need to decide how implement them.
[Design](https://www.figma.com/file/FxmwqO6LRg7tOVXrZqMMG0/Neural-Notes-Design-v.0.3)

Main when MindMap shown:
![Screenshot_21](https://user-images.githubusercontent.com/19979138/93706978-e0b3b900-fb33-11ea-91b0-c15738e569b4.png)

When Note open/edit/create:
![Screenshot_22](https://user-images.githubusercontent.com/19979138/93706999-fcb75a80-fb33-11ea-8199-a6eff2705967.png)

When changing parent:
![Screenshot_23](https://user-images.githubusercontent.com/19979138/93707009-12c51b00-fb34-11ea-9133-2f48e875bdc8.png)

When uploads screen open:
![Screenshot_26](https://user-images.githubusercontent.com/19979138/93707095-8ebf6300-fb34-11ea-9c42-3483394ad662.png)

And for search:
![Screenshot_25](https://user-images.githubusercontent.com/19979138/93707105-9d0d7f00-fb34-11ea-9c13-09c8c1519de3.png)
![Screenshot_24](https://user-images.githubusercontent.com/19979138/93707110-a0086f80-fb34-11ea-9d83-a34a23da3d56.png)

To implement them, I plan to use [Material-ui AppBar component](https://material-ui.com/components/app-bar/).
But still I have questions:
Do I need to use a pure MUI component in each of these cases?
Or should I create three custom MUI-component and then reuse them (i.e. FIRST for note open/edit/create& changing parent&uploads screen; SECOND for Main MindMap; THIRD for search)?

**Comment by DarthVanger** [comment]
The variants are quite different. I think it's okay to implement the topbar for each page separately.
