### ISSUE TITLE
Remove <OpenFileButtonComponent>

### ISSUE THREAD

**Issue by kvoncode** [DarthVanger/NeuralNotes#151]
Currently <OpenFileButtonComponent> serves no function and even not rendering in main UI, I suppose it duplicates <UploadButton> component. If you will give permission I will delete it.

It looks like following: the text "Open in G-Drive" and some styles

![Screenshot 2020-10-16 16:43:53](https://user-images.githubusercontent.com/45026388/96227632-58f48980-0fcf-11eb-9c39-66d9a900d24d.png)

**Comment by DarthVanger** [comment]
Which component does it duplicate?
It is shown on the main ui if you upload a file and then select it. For
notes we show note content editor, but for files we show "open in google
drive" button.
Its function is to open file in google drive. It is a link to the uploaded
file on google drive. Why do you think it serves no function?

**Comment by kvoncode** [comment]
You mean it should work this way or it works this way?
Currenlty I found no logic connected with this component. Only 2 files 1 is button with text, second is styled components
![Screenshot 2020-10-16 16:43:53](https://user-images.githubusercontent.com/45026388/96229339-b8539900-0fd1-11eb-835c-de36ced79d72.png)

**Comment by kvoncode** [comment]
Sorry wrong image
![Screenshot 2020-10-16 16:58:58](https://user-images.githubusercontent.com/45026388/96229368-c3a6c480-0fd1-11eb-81f2-af9b370f0b2a.png)

**Comment by kvoncode** [comment]
I thought it is intended to be "upload file button"

**Comment by DarthVanger** [comment]
>You mean it should work this way or it works this way?

We had a button which worked this way :) Regarding `OpenFileButtonComponent.js` you're right, currently it has no functionality, only text and styles.

Using `git blame` I can see it was created by @TomaTomoe 
```
366bf20c (Toma Tomoe 2020-07-21 18:02:20 +0300 1)
```

The commit message is
```
commit 366bf20c9b4d98c07fd347712bf4face338a4779 (origin/117-OF-buttonDesign)
Author: Toma Tomoe <denysiuk.tina@gmail.com>
Date:   Tue Jul 21 18:02:20 2020 +0300

    Open file: implement design of 'Open in G-Drive' button

    - Create OpenFileButtonComponent without functionality;
    - Implement design for OpenFileButtonComponent;

    Resolve #117
```

Ticket #117 indeed said to implement this button without any functionality, only design. And it links to issue #116 to show this button when user selects a file. But in that issue the design for this button is different...

@TomaTomoe do we still need this component? Or should we delete it, since it implements the old design, which is not needed anymore? And create another issue to implement the same button but with the new design?

**Comment by DarthVanger** [comment]
The old, working button, is currently covered by the text editor. I can see it only if I change `top: 0` to `top: 50px` for the note editor... :)

![image](https://user-images.githubusercontent.com/6686679/96234439-1e282c80-0fa2-11eb-976c-6302367c08fc.png)

**Comment by DarthVanger** [comment]
Code for the working button (link) shown above is here: https://github.com/DarthVanger/NeuralNotes/blob/7e483dcfc80f3b3df1692219df265a0927085289/src/components/NotesContentEditor/NotesContentEditorComponent.js#L51

**Comment by kvoncode** [comment]
Commented in render tree in https://github.com/DarthVanger/NeuralNotes/tree/addnote-page
