### ISSUE TITLE
Replace: <NotesContentEditorComponent>

### ISSUE THREAD

**Issue by kvoncode** [DarthVanger/NeuralNotes#152]
Currently this component serves little to no function and duplicating the NoteDetailsContainer, which actually renders the UI.

The component looks like this:
![Screenshot 2020-10-16 17:19:36](https://user-images.githubusercontent.com/45026388/96233997-caced200-0fd3-11eb-9618-bed27889aa6a.png)

The app without this component looks fine
![123](https://user-images.githubusercontent.com/45026388/96234940-1766dd00-0fd5-11eb-89f1-34c1b8abfde2.png)

My suggestion is 1) delete this component 

Please comment. If you agree I will start refactoring

**Comment by DarthVanger** [comment]
> 3) each node (element) that is file and should be opened in GD, open in GD on 1 click

When a file is selected, it can be deleted, and we can change parent for it. Opening it in GD on 1 click would provide no ability to delete it or change parent. So we have a separate button to open it in Google Drive, as per [design](https://www.figma.com/file/FxmwqO6LRg7tOVXrZqMMG0/Neural-Notes-Design-v.0.3?node-id=212%3A836):

![image](https://user-images.githubusercontent.com/6686679/96235544-9c390300-0fa3-11eb-85c3-06fd3152a74f.png)

>1) delete this component

I believe we shouldn't delete it, as we still have it in the new design.

>2) extract NoteDetailsContainer to "addnote" page 

That's right, it should be done as part of #100 . Btw, "addnote" page is the same as "note details" page and "edit note page". It serves all this 3 functions at the same time. So I would call it simply "note page".

**Comment by kvoncode** [comment]
Excuse me I want to be clear: there is 2 components 1) NotesContentEditorComponent and 2)NoteDetailsContainer. I suggested deleting first and extract second. both have text area elements, but only second renders. I can make bottom nav bar as in screenshot, it will be separate component from editing text.

Currently I try to extract textarea element to "note page" and refactor on my way.

**Comment by DarthVanger** [comment]
That's great @kvoncode , I like being clear and sorting things out :) Keep asking!

>there is 2 components 1) NotesContentEditorComponent and 2)NoteDetailsContainer

I believe you mean `NoteDetailsComponent`? Each of the 2 components have `...Component.js` and `...Container.js` files.

I think you're right that we should delete `NotesContentEditor`. Looks like the only useful thing it does, compared to `NoteDetails`, is that it has `debounce` (while `NoteDetails` sends http requests on every change without any debounce, if I'm not mistaken).

**Comment by kvoncode** [comment]
Ok for now I will keep it just in case we need something, but will comment it from render tree, and start to implement "note page". We always can delete it later when we have complete app.

**Comment by DarthVanger** [comment]
> I can make bottom nav bar as in screenshot

Please don't do it :) We have a cheaper developer who is responsible for styling and using Material UI components. Your responsibility is to handle more complicated stuff, like organizing the flow of http requests (working with redux-saga).

We will have separate task to add the bottom bar. For now let's focus on creating a new page, moving the note name and content editors there, and making them work properly.

**Comment by kvoncode** [comment]
Yes, of course. I just realized other person is working on it through PR page and git kraken graph

**Comment by DarthVanger** [comment]
>Currently I try to extract textarea element to "note page" and refactor on my way.

Not sure you need to extract it. I think you just need to render `NoteDetailsComponent` on the new page :)
Also not sure what are you refactoring there :) but ok, please make a WIP MR as soon as you have something to show, so we can align on what we want to do.

**Comment by kvoncode** [comment]
That exactly what I mean by extract. Of course, I will send PR

**Comment by kvoncode** [comment]
Commented in render tree in https://github.com/DarthVanger/NeuralNotes/tree/addnote-page
