### ISSUE TITLE
Refactor "thought-storage-api.js"

### ISSUE THREAD

**Issue by DarthVanger** [DarthVanger/NeuralNotes#16]
File to refactor:
https://github.com/DarthVanger/NeuralNotes/blob/master/src/storage/thought-storage-api.js

1. Rename to `note-storage-api`
  - all occurrences of "thought" in this file should be replaced with "note" as well. For example parameters names in `function create(thought, parentThought)`.
  https://github.com/DarthVanger/NeuralNotes/blob/master/src/storage/thought-storage-api.js#L488
2. Delete commented code
  - https://github.com/DarthVanger/NeuralNotes/blob/master/src/storage/thought-storage-api.js#L159
  - https://github.com/DarthVanger/NeuralNotes/blob/master/src/api/google-drive-api.js#L84
  - etc
3. File has methods of different responsibility / abstraction level:
  - `create()` creates a note
  - `createDirectory()` creates a directory on google drive directly calling google client and passing google drive specific meta data `"mimeType": "application/vnd.google-apps.folder"`.
  Methods like `createDirectory()` should be moved out from this file.
  For example `google-drive-api.js` looks like a better place for methods like `createDirectory()` https://github.com/DarthVanger/NeuralNotes/blob/master/src/api/google-drive-api.js.
  `note-storage-api` should not call google drive api directly.

**Comment by SamueleA** [comment]
I'm going to take this.

**Comment by DarthVanger** [comment]
Okay. Yeah that's an easy one, good start.

That guy who was going to remove bower just said he realized he has no time
for this work.
So you're the only one working on this right now.

**Comment by DarthVanger** [comment]
Everything done except `note-storage-api` still having methods like `updateFileName()` - it shouldn't provide such a low level api to work with files. Fine for now.
