### ISSUE TITLE
delete: stale branches

### ISSUE THREAD

**Issue by kvoncode** [DarthVanger/NeuralNotes#160]
Currently there is at least 3 branches that stale and can be deleted safely

![Screenshot 2020-10-19 13:06:28](https://user-images.githubusercontent.com/45026388/96400561-0653e100-120c-11eb-91c6-425cbba7a09a.png)

Will much appreciate as it will allow me to more freely navigate between branches

**Comment by DarthVanger** [comment]
@TomaTomoe please delete your stale branches.
