### ISSUE TITLE
Show last viewed note on startup

### ISSUE THREAD

**Issue by DarthVanger** [DarthVanger/NeuralNotes#93]
When the user opens the app, he/she should see the last viewed note and its children (currently when the app is opened, it shows the root note ("NeuralNotes") always).

The last viewed noteId can be saved to localStorage for example.

**Comment by jpalacio0612** [comment]
Hello Ivan.

I will take this issue.

**Comment by DarthVanger** [comment]
> Hello Ivan.
> 
> I will take this issue.

Okay! :) Assigned the issue to use and moved to `In progress`

**Comment by jpalacio0612** [comment]
Hi Ivan.

I finish the first part to resolve this issue. But I have a question.
At the moment, to be more precise, I am storing the id of the last note in the localstorage and when I logout I clean the localstorage to avoid any error in case another different user enters the same browser. Is this operation correct? or the localstorage should persist even after logging out. 
This code is in a new branch called lastViewedNote

![lastnote](https://user-images.githubusercontent.com/65427911/96075915-b8d51e00-0e71-11eb-8c47-8e0f252c4cc7.gif)

**Comment by DarthVanger** [comment]
Hi Jonathan!
Hm good question :)
I think you're right we should clear it when user logs out.

**Comment by DarthVanger** [comment]
The 2nd part of the task was moved to a separate issue: https://github.com/DarthVanger/NeuralNotes/issues/154
